// Espelha a navegação do handoff de design (Claude Design) do Potiguar Mix.
export const NAV = [
  { key: 'meudia', label: 'MEU DIA', items: [
    { id: 'dia-painel', label: 'Painel de Priorização' },
  ] },
  { key: 'comercial', label: 'COMERCIAL', items: [
    { id: 'crm-clientes', label: 'Clientes' },
  ] },
  { key: 'qualidade', label: 'QUALIDADE', items: [
    { id: 'prod-tracos', label: 'Traço / Formulação' },
    { id: 'prod-qualidade', label: 'Controle de Qualidade' },
    { id: 'tech-coleta', label: 'Agenda de Coleta CP' },
    { id: 'tech-ruptura', label: 'Agenda de Ruptura CP' },
  ] },
  { key: 'producao', label: 'PRODUÇÃO', items: [
    { id: 'prod-ordens', label: 'Ordens de Produção' },
    { id: 'prod-bomba', label: 'Serviço de Bomba' },
    { id: 'prod-dosagem', label: 'Apontamento de Dosagem' },
    { id: 'prod-expedicao', label: 'Expedição / Carregamento' },
  ] },
  { key: 'compras', label: 'COMPRAS', items: [
    { id: 'comp-solicitacao', label: 'Solicitação de Compra' },
    { id: 'comp-cotacao', label: 'Cotação' },
    { id: 'comp-aprovacoes', label: 'Aprovações' },
    { id: 'comp-pedidos', label: 'Pedidos' },
    { id: 'comp-fornecedores', label: 'Fornecedores' },
    { id: 'comp-fiscal', label: 'Documentos Fiscais' },
    { id: 'comp-medicao', label: 'Fechamento de Medição' },
    { id: 'comp-estoque', label: 'Estoque / Kardex' },
  ] },
  { key: 'financeiro', label: 'FINANCEIRO', items: [
    { id: 'fin-dashboard', label: 'Dashboard' },
    { id: 'fin-pagar', label: 'Contas a Pagar' },
    { id: 'fin-receber', label: 'Contas a Receber' },
    { id: 'fin-fluxo', label: 'Fluxo de Caixa' },
    { id: 'fin-medicao-rps', label: 'Medição a partir de RPS' },
    { id: 'fin-conciliacao', label: 'Conciliação Bancária' },
    { id: 'fin-comissoes', label: 'Comissões' },
  ] },
  { key: 'relatorios', label: 'RELATÓRIOS', items: [
    { id: 'fin-dre', label: 'DRE' },
    { id: 'fin-fechamento', label: 'Fechamento Mensal' },
    { id: 'fin-pagamentos', label: 'Pagamentos Liquidados' },
    { id: 'fin-notas', label: 'Notas Fiscais por Emissão' },
  ] },
  { key: 'obras', label: 'OBRAS / OPERAÇÃO', items: [
    { id: 'obras-dashboard', label: 'Dashboard Operacional' },
    { id: 'obras-frota', label: 'Manutenção de Frota' },
    { id: 'obras-andamento', label: 'Obras em Andamento' },
    { id: 'obras-ocorrencias', label: 'Ocorrências' },
  ] },
];

export const TITLES = {
  'dia-painel': 'Meu Dia — Painel de Priorização',
  'crm-clientes': 'Clientes',
  'prod-tracos': 'Traço / Formulação do Concreto',
  'prod-qualidade': 'Controle de Qualidade',
  'tech-coleta': 'Agenda de Coleta — Corpo de Prova',
  'tech-ruptura': 'Agenda de Ruptura — Corpo de Prova',
  'prod-ordens': 'Ordens de Produção',
  'prod-bomba': 'Serviço de Bomba',
  'prod-dosagem': 'Apontamento de Dosagem por Usina',
  'prod-expedicao': 'Expedição / Carregamento',
  'comp-solicitacao': 'Solicitação de Compra',
  'comp-cotacao': 'Cotações',
  'comp-aprovacoes': 'Aprovações Pendentes',
  'comp-pedidos': 'Pedidos',
  'comp-fornecedores': 'Fornecedores',
  'comp-fiscal': 'Gestão de Documentos Fiscais',
  'comp-medicao': 'Fechamento de Medição de Fornecedores',
  'comp-estoque': 'Estoque / Kardex por Unidade',
  'fin-dashboard': 'Dashboard Financeiro',
  'fin-pagar': 'Contas a Pagar',
  'fin-receber': 'Contas a Receber',
  'fin-fluxo': 'Fluxo de Caixa Projetado',
  'fin-medicao-rps': 'Medição a partir de RPS',
  'fin-conciliacao': 'Conciliação Bancária',
  'fin-comissoes': 'Comissões',
  'fin-dre': 'Demonstração do Resultado do Exercício (DRE)',
  'fin-fechamento': 'Fechamento Mensal',
  'fin-pagamentos': 'Relatório de Pagamentos',
  'fin-notas': 'Relatório Contábil por Emissão de NF',
  'obras-dashboard': 'Dashboard Operacional das Usinas',
  'obras-frota': 'Gestão de Manutenção de Frota',
  'obras-andamento': 'Obras em Andamento',
  'obras-ocorrencias': 'Registro de Ocorrências',
};
